### ISSUE TITLE
database.py improperly uses SatCat.sat_cat_id

### ISSUE THREAD

**Issue by interplanetarychris** [TruSat/trusat-backend#106]
A few references which join to the SatCat table, improperly join to the internal table counter (SatCat.sat_cat_id) instead of the norad number (SatCat.norad_num)

Specifically:

https://github.com/TruSat/trusat-backend/blob/b1c15a81bcfcdd625149ec0dab16751467f25cb4/database.py#L365

https://github.com/TruSat/trusat-backend/blob/b1c15a81bcfcdd625149ec0dab16751467f25cb4/database.py#L3458

https://github.com/TruSat/trusat-backend/blob/b1c15a81bcfcdd625149ec0dab16751467f25cb4/database.py#L3594

**Comment by Kmoneal** [comment]
Now being addressed in #105
