### ISSUE TITLE
"Priorities" category is returning suspect results

### ISSUE THREAD

**Issue by interplanetarychris** [TruSat/trusat-backend#109]
The trusat_priorities.txt TLE file has approximately the same number of entries as the trusat_all.txt file.  

As priorities is currently coded to be satellites not updated in the last 30 days, the "priorities" list should be quite a bit smaller than the "all" list given the number of recent observations.

**Comment by Kmoneal** [comment]
I can't find any TLEs that are younger than the last 30 days (TLE.epoch) when I use the `ALL` query. They both put the upper cap at 365 days so it looks like it should be the same. Maybe something preventing the more recent TLEs from being pulled. Just wanted to update this based on a quick check. Will keep looking into it.

**Comment by interplanetarychris** [comment]
There are definitely hundreds of TLEs newer than 30 days.  Perhaps the time difference query is not behaving appropriately?

**Comment by interplanetarychris** [comment]
Ah - the issue could be that TLEs haven't been updated on Devvy in some time, which would explain this behavior.  I could clone over the production database to verify.
