### ISSUE TITLE
Some satellites showing up twice in Super-Categories

### ISSUE THREAD

**Issue by interplanetarychris** [TruSat/trusat-backend#110]
When browsing "Super-Categories" in the PR https://github.com/TruSat/trusat-frontend/pull/287 some satellites are showing up twice.

https://devvymcdevface.trusat.org/catalog/misc
44032, 43548 showing up twice in Super Category "Misc" 
43021 on next page
42726, 43547 on next page

44032, 43548 do not appear to be duplicated in sub-category: https://devvymcdevface.trusat.org/catalog/cubesat

**Comment by Kmoneal** [comment]
Queries were not being grouped. Going to double check but added a grouping in commit: https://github.com/TruSat/trusat-backend/pull/108/commits/1013f093d51fc10e2b8b3d4d7b53ff0535788b7b

**Comment by interplanetarychris** [comment]
@Kmoneal Please link the appropriate PR to this issue, so that it can be closed when @johngribbin deploys PR https://github.com/TruSat/trusat-frontend/pull/298

**Comment by interplanetarychris** [comment]
The items mentioned initially appear to be resolved in the current environment on Devvy (wish we had a release candidate # to reference)

**Comment by Kmoneal** [comment]
Resolved in #108
